---
monit_host: localhost # the host of Monit, defaults to localhost
monit_port: 2812 # the Monit port, defaults to 2812
ssl: false #  should we use SSL for the connection to Monit (default: false))
auth: true # should authentication be used for Monit, defaults to false
username: foo # username for authentication
password: bar # password for authentication
collectd_host: localhost # the host for Collectd, defaults to localhost
collectd_port: 25826 #  the Collectd port, defaults to 25826
interval: 10 # The Collectd interval to retrieve data, defaults to 10
debug: false # turns on or off debug, defaults to false
